# Generated by Django 4.0.3 on 2022-05-02 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerProfile',
            new_name='Customer',
        ),
    ]
